apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: rook-ceph-mcp-dev
  namespace: rook-ceph-dev

resources:
  - apps/rook-operator.yaml
  - apps/monitoring-stack.yaml
  - apps/security.yaml
  - cluster-manifests/dev-ceph-cluster.yaml
  - cluster-manifests/block-pool.yaml
  - cluster-manifests/object-store.yaml

commonLabels:
  app.kubernetes.io/name: rook-ceph
  app.kubernetes.io/instance: rook-ceph-mcp-dev
  app.kubernetes.io/component: storage
  app.kubernetes.io/part-of: rook-ceph
  app.kubernetes.io/managed-by: rook-ceph-mcp
  environment: development

namespace: rook-ceph-dev

namePrefix: dev-
nameSuffix: -dev

images:
  - name: rook/ceph
    newTag: v1.12.0
  - name: quay.io/ceph/ceph
    newTag: v18.2.0

configMapGenerator:
  - name: rook-ceph-config
    literals:
      - ROOK_LOG_LEVEL=DEBUG
      - ROOK_CEPH_STATUS_CHECK_INTERVAL=30s
      - ROOK_MON_HEALTHCHECK_INTERVAL=30s
      - ROOK_DISCOVER_DEVICES_INTERVAL=30m
      - ROOK_ALLOW_MULTIPLE_FILESYSTEMS=true
      - ROOK_ENABLE_DISCOVERY_DAEMON=true

secretGenerator:
  - name: rook-ceph-mon
    type: Opaque
    literals:
      - mon-secret=dev-base64-encoded-secret
      - admin-secret=dev-base64-encoded-admin-secret

patches:
  - target:
      kind: Deployment
      name: rook-ceph-operator
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 512Mi
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ROOK_ENABLE_DEBUG_MODE
          value: "true"

replicas:
  - name: rook-ceph-operator
    count: 1

vars:
  - name: ROOK_NAMESPACE
    objref:
      kind: Namespace
      name: rook-ceph-dev
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name