version: '3.8'

services:
  rook-ceph-mcp-http:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rook-ceph-mcp-http
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    volumes:
      # Mount kubeconfig for cluster access
      - ${HOME}/.kube/config:/app/.kube/config:ro
    healthcheck:
      test: ["CMD", "node", "-e", "const http = require('http'); const req = http.request({hostname: 'localhost', port: 3000, path: '/health', method: 'GET'}, (res) => { process.exit(res.statusCode === 200 ? 0 : 1); }); req.on('error', () => process.exit(1)); req.end();"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  rook-ceph-mcp-stdio:
    build:
      context: .
      dockerfile: Dockerfile.stdio
    container_name: rook-ceph-mcp-stdio
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=production
    volumes:
      # Mount kubeconfig for cluster access
      - ${HOME}/.kube/config:/app/.kube/config:ro
    command: ["npm", "run", "start:stdio"]