apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: rook-ceph-mcp-production
  namespace: rook-ceph

resources:
  - apps/rook-operator.yaml
  - apps/monitoring-stack.yaml
  - apps/security.yaml
  - cluster-manifests/ceph-cluster.yaml
  - cluster-manifests/block-pool.yaml
  - cluster-manifests/object-store.yaml

commonLabels:
  app.kubernetes.io/name: rook-ceph
  app.kubernetes.io/instance: rook-ceph-mcp-production
  app.kubernetes.io/component: storage
  app.kubernetes.io/part-of: rook-ceph
  app.kubernetes.io/managed-by: rook-ceph-mcp
  environment: production

namespace: rook-ceph

namePrefix: prod-
nameSuffix: -prod

images:
  - name: rook/ceph
    newTag: v1.12.0
  - name: quay.io/ceph/ceph
    newTag: v18.2.0

configMapGenerator:
  - name: rook-ceph-config
    literals:
      - ROOK_LOG_LEVEL=WARN
      - ROOK_CEPH_STATUS_CHECK_INTERVAL=60s
      - ROOK_MON_HEALTHCHECK_INTERVAL=45s
      - ROOK_DISCOVER_DEVICES_INTERVAL=60m
      - ROOK_ALLOW_MULTIPLE_FILESYSTEMS=false
      - ROOK_ENABLE_DISCOVERY_DAEMON=true
      - ROOK_ENABLE_MACHINE_DISRUPTION_BUDGET=true

secretGenerator:
  - name: rook-ceph-mon
    type: Opaque
    literals:
      - mon-secret=production-base64-encoded-secret
      - admin-secret=production-base64-encoded-admin-secret

patches:
  - target:
      kind: Deployment
      name: rook-ceph-operator
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 1000m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ROOK_ENABLE_METRICS
          value: "true"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ROOK_ENABLE_AUDIT_LOGGING
          value: "true"

replicas:
  - name: rook-ceph-operator
    count: 2

vars:
  - name: ROOK_NAMESPACE
    objref:
      kind: Namespace
      name: rook-ceph
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name