apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3
    requireSafeReplicaSize: true
  parameters:
    pg_num: "128"
    pgp_num: "128"
  mirroring:
    enabled: false
    mode: image
    snapshotSchedules: []
  statusCheck:
    mirror:
      disabled: false
      interval: 60s
      timeout: 5m
  quotas:
    maxObjects: 1000000
    maxBytes: 1000000000000