apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: my-store
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
    parameters:
      pg_num: "32"
      pgp_num: "32"
  dataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
    parameters:
      pg_num: "128"
      pgp_num: "128"
  preservePoolsOnDelete: true
  gateway:
    type: s3
    sslCertificateRef: ""
    port: 80
    securePort: 443
    instances: 1
    priorityClassName: system-cluster-critical
    placement:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: rook-ceph-rgw
    annotations:
      key: value
    labels:
      key: value
    resources:
      limits:
        cpu: 2000m
        memory: 2Gi
      requests:
        cpu: 1000m
        memory: 1Gi
    caBundleRef: ""
  protocols:
    s3:
      enabled: true
      authUseKeystone: false
    swift:
      enabled: false
      authUseKeystone: false
  healthCheck:
    bucket:
      disabled: false
      interval: 60s
  security:
    kms:
      connectionDetails: {}
      tokenSecretName: ""
    s3:
      connectionDetails: {}
      tokenSecretName: ""
  sharedPools:
    metadataPoolName: ""
    dataPoolName: ""
    preserveRadosNamespaceDataOnDelete: false
  zone:
    name: ""